//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shkila.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connections
    {
        public long GUID { get; set; }
        public string Tag { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<long> VehicleID { get; set; }
        public Nullable<long> ItemID { get; set; }
        public Nullable<long> TransportID { get; set; }
        public Nullable<long> DriverID { get; set; }
        public Nullable<long> InSiteID { get; set; }
        public Nullable<long> OutSiteID { get; set; }
        public Nullable<long> CustomerID { get; set; }
    }
}
