//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shkila.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsWeighingLines
    {
        public long GUID { get; set; }
        public Nullable<long> GoodsWeighingID { get; set; }
        public Nullable<long> ScaleID { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<long> ItemID { get; set; }
    }
}
