//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shkila.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sites
    {
        public long GUID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
        public bool IsAddInForm { get; set; }
    }
}
