//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shkila.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiclesWeighing
    {
        public long GUID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<long> ScaleID { get; set; }
        public Nullable<long> VehicleID { get; set; }
        public Nullable<long> ItemID { get; set; }
        public Nullable<long> TransportID { get; set; }
        public Nullable<decimal> InWeight { get; set; }
        public Nullable<decimal> OutWeight { get; set; }
        public Nullable<decimal> Netto { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public Nullable<System.DateTime> OutDate { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public Nullable<long> InSiteID { get; set; }
        public Nullable<long> OutSiteID { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsManual { get; set; }
        public Nullable<long> CertificateID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<int> WeighingMode { get; set; }
        public Nullable<long> DriverID { get; set; }
        public string Tag { get; set; }
        public string Reference { get; set; }
    }
}
