//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeightModificationAlarm
{
    using System;
    
    public partial class sp_GetUsers_Result
    {
        public bool Active { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public long GUID { get; set; }
        public string ID { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public string Username { get; set; }
        public Nullable<long> DefaultScaleID { get; set; }
        public Nullable<long> DefaultFormID { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public Nullable<long> PermissionID { get; set; }
        public Nullable<long> DriverID { get; set; }
        public string CompanyName { get; set; }
        public bool CompanyIsOwner { get; set; }
        public bool CompanyIsSuper { get; set; }
        public string ScaleName { get; set; }
        public string FormName { get; set; }
        public string FormLink { get; set; }
        public string PermissionName { get; set; }
        public string DriverName { get; set; }
    }
}
