//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shkila.Model
{
    using System;
    
    public partial class sp_GetSilos_Result
    {
        public bool Active { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public long GUID { get; set; }
        public Nullable<long> ScaleID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> MaxCapacity { get; set; }
        public string SiteName { get; set; }
        public string CompanyName { get; set; }
        public bool IsLoad { get; set; }
        public bool IsUnload { get; set; }
        public Nullable<double> LoadInterval { get; set; }
        public Nullable<long> LoadIntervalTime { get; set; }
        public Nullable<double> UnloadInterval { get; set; }
        public Nullable<long> UnloadIntervalTime { get; set; }
        public Nullable<long> UnitID { get; set; }
        public string UnitName { get; set; }
        public Nullable<double> UnitMGConversion { get; set; }
        public bool IsLogWeight { get; set; }
        public Nullable<long> LogWeightTime { get; set; }
        public string ScaleName { get; set; }
    }
}
