//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basalt_v2
{
    using System;
    
    public partial class sp_GetScales_Result
    {
        public bool Active { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public long GUID { get; set; }
        public string MAC { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Weight { get; set; }
        public Nullable<System.DateTime> WeightDate { get; set; }
        public string Name { get; set; }
        public Nullable<long> ScalesTypeID { get; set; }
        public bool IsDemo { get; set; }
        public Nullable<long> UnitID { get; set; }
        public Nullable<long> OwnerID { get; set; }
        public string CompanyName { get; set; }
        public string ScalesTypeName { get; set; }
        public string UnitName { get; set; }
    }
}
