//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shkila.Model
{
    using System;
    
    public partial class sp_GetCompaniesSettings_Result
    {
        public Nullable<long> CompanyID { get; set; }
        public long GUID { get; set; }
        public Nullable<long> SettingID { get; set; }
        public string SettingLink { get; set; }
        public string SettingName { get; set; }
        public string CompanyName { get; set; }
        public long AllowedRows { get; set; }
    }
}
