//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shkila.Model
{
    using System;
    
    public partial class sp_GetVehicles_Result
    {
        public bool Active { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public long GUID { get; set; }
        public string CompanyName { get; set; }
        public string LicenseNumber { get; set; }
        public Nullable<decimal> Tare { get; set; }
        public string CustomerName { get; set; }
        public string TransportName { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<long> TransportID { get; set; }
        public bool IsAddInForm { get; set; }
        public long WeighingModeID { get; set; }
    }
}
