//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shkila.Model
{
    using System;
    
    public partial class sp_GetPermissionsTablesInnerPermissions_Result
    {
        public Nullable<long> TablesInnerPermissionID { get; set; }
        public long GUID { get; set; }
        public Nullable<long> PermissionID { get; set; }
        public string TablesInnerPermissionName { get; set; }
        public string TableName { get; set; }
        public string PermissionName { get; set; }
        public string CompanieName { get; set; }
        public long TableID { get; set; }
        public Nullable<bool> Read { get; set; }
        public Nullable<bool> Write { get; set; }
    }
}
