//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shkila.Model
{
    using System;
    
    public partial class sp_GetSuppliersContacts_Result
    {
        public bool Active { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public long GUID { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> SupplierID { get; set; }
        public Nullable<long> SupplierCompanyID { get; set; }
        public string SupplierName { get; set; }
        public string CompanyName { get; set; }
    }
}
