//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shkila.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompaniesSystemSettings
    {
        public long GUID { get; set; }
        public int LanguageID { get; set; }
        public string LogoPath { get; set; }
        public string DataFolder { get; set; }
        public string ImagesFolder { get; set; }
        public string SystemLogoPath { get; set; }
        public Nullable<long> CompanyID { get; set; }
    }
}
